name: Matrix Test
on:
  push:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.colors.outputs.colors }}

    steps:
      - name: Define Colors
        id: colors
        run: |
          echo 'colors=["red", "green", "blue", "yellow", "purple", "orange", "pink", "brown", "black", "white"]' >> "$GITHUB_OUTPUT"

  call-reusable-workflow:
    needs: define-matrix
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}
    uses: ./.github/workflows/produce-consume.yaml
    with:
      color: ${{ matrix.color }}
